#!/usr/bin/env node
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { pathToFileURL } from "node:url";

const root = process.cwd();
const manifest = JSON.parse(readFileSync(join(root, "integrations.manifest.json"), "utf8"));

function usage() {
  console.error(`Usage:
  npm run vendor:tools -- --package <package-name> --out <tools-dir> [--tool <tool-name> ...]
  npm run vendor:tools -- --all --out <tools-dir>

Examples:
  npm run vendor:tools -- --package @chidori/integrations-web --tool tavily_search --out ../my-agent/tools
  npm run vendor:tools -- --all --out ../my-agent/tools
`);
  process.exit(2);
}

function parseArgs(argv) {
  const parsed = { packageNames: [], toolNames: [], all: false, out: "" };
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index];
    if (arg === "--package") {
      parsed.packageNames.push(argv[++index]);
    } else if (arg === "--tool") {
      parsed.toolNames.push(argv[++index]);
    } else if (arg === "--out") {
      parsed.out = argv[++index];
    } else if (arg === "--all") {
      parsed.all = true;
    } else {
      usage();
    }
  }
  if (!parsed.out || (!parsed.all && parsed.packageNames.length === 0)) {
    usage();
  }
  return parsed;
}

function stripModuleSyntax(source) {
  return source
    .replace(/^import[\s\S]*?;\n/gm, "")
    .replace(/^export /gm, "")
    .replace(/\/\/# sourceMappingURL=.*\n?/g, "");
}

function safeToolFileName(toolName) {
  return `${toolName.replace(/[^a-zA-Z0-9_-]/g, "_")}.ts`;
}

async function exportedTools(packageEntry) {
  const moduleUrl = pathToFileURL(resolve(root, packageEntry.path, "dist", "index.js")).href;
  const module = await import(`${moduleUrl}?moduleVersion=${Date.now()}`);
  const tools = new Map();
  for (const [exportName, value] of Object.entries(module)) {
    if (value && typeof value === "object" && value.tool && typeof value.run === "function") {
      tools.set(value.tool.name, exportName);
    }
  }
  return tools;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const outDir = resolve(root, args.out);
  mkdirSync(outDir, { recursive: true });

  const coreSource = stripModuleSyntax(readFileSync(join(root, "packages/core/dist/index.js"), "utf8"));
  const packageEntries = manifest.packages.filter((entry) => {
    return args.all || args.packageNames.includes(entry.name);
  });
  if (packageEntries.length === 0) {
    throw new Error("No manifest packages matched the requested package names");
  }

  const written = [];
  for (const entry of packageEntries) {
    const tools = await exportedTools(entry);
    const selectedToolNames = args.toolNames.length > 0
      ? (entry.tools ?? []).filter((toolName) => args.toolNames.includes(toolName))
      : (entry.tools ?? []);
    if (selectedToolNames.length === 0) {
      continue;
    }

    const packageSource = stripModuleSyntax(readFileSync(join(root, entry.path, "dist", "index.js"), "utf8"));
    for (const toolName of selectedToolNames) {
      const exportName = tools.get(toolName);
      if (!exportName) {
        throw new Error(`${entry.name}: unable to find exported tool object for ${toolName}`);
      }
      const filename = safeToolFileName(toolName);
      const body = `// Generated by chidori-integrations/scripts/vendor-tools.mjs.
// Source package: ${entry.name}

${coreSource}

${packageSource}

export const tool = ${exportName}.tool;

export async function run(args, chidori) {
  return ${exportName}.run(args, chidori);
}
`;
      writeFileSync(join(outDir, filename), body);
      written.push(join(outDir, filename));
    }
  }

  if (written.length === 0) {
    throw new Error("No tools were written. Check --package and --tool filters.");
  }
  for (const file of written) {
    console.log(file);
  }
}

main().catch((error) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exit(1);
});
